version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nestjs-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - PORT=3000
      - GOOGLE_CLIENT_ID=your_google_client_id_here
      - GOOGLE_CLIENT_SECRET=your_google_client_secret_here
      - GOOGLE_CALLBACK_URL=http://localhost:3000/google/callback
      - FRONTEND_URL=http://localhost:3001
      # Add these for mobile testing
      - GOOGLE_CALLBACK_URL_MOBILE=http://192.168.0.199:3000/google/callback
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: pg-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
